import {
  LuActivity,
  LuAlignCenter,
  LuAperture,
  LuBadge,
  LuBadgeCheck,
  LuBell,
  LuBox,
  LuCaseSensitive,
  LuChartNoAxesColumn,
  LuCheck,
  LuChevronDown,
  LuChevronsUpDown,
  LuCircle,
  LuCircleCheck,
  LuCircleDashed,
  LuCode,
  LuCombine,
  LuContainer,
  LuCreditCard,
  LuEllipsis,
  LuEqual,
  LuExternalLink,
  LuFileImage,
  LuFileText,
  LuGalleryHorizontal,
  LuGalleryVertical,
  LuGrid3X3,
  LuGroup,
  LuHash,
  LuHighlighter,
  LuImage,
  LuInbox,
  LuInfo,
  LuKanban,
  LuKeyboard,
  LuLayers,
  LuLayoutDashboard,
  LuLayoutGrid,
  LuLayoutTemplate,
  LuLetterText,
  LuLibrary,
  LuLink,
  LuList,
  LuListChecks,
  LuListCollapse,
  LuLoader,
  LuLock,
  LuMessageSquareWarning,
  LuMousePointerClick,
  LuMove,
  LuMoveHorizontal,
  LuNavigation,
  LuNotebookText,
  LuPackage,
  LuPalette,
  LuPanelLeft,
  LuPanelTop,
  LuPanelTopOpen,
  LuPanelsTopLeft,
  LuPenLine,
  LuPilcrow,
  LuPower,
  LuQuote,
  LuRoute,
  LuRows2,
  LuRows3,
  LuScrollText,
  LuSection,
  LuSeparatorHorizontal,
  LuSlidersHorizontal,
  LuSquareCheck,
  LuSquareMousePointer,
  LuTable,
  LuTimer,
  LuToggleLeft,
  LuTriangle,
  LuTriangleAlert,
  LuType,
  LuUser,
  LuX,
} from 'react-icons/lu';

export const IconMap = {
  accordion: LuListCollapse,
  'alert-dialog': LuTriangleAlert,
  'app-layout': LuLayoutDashboard,
  avatar: LuUser,
  badge: LuBadgeCheck,
  'bg-image': LuFileImage,
  box: LuBox,
  blockquote: LuQuote,
  breadcrumbs: LuRoute,
  button: LuMousePointerClick,
  callout: LuMessageSquareWarning,
  card: LuCreditCard,
  center: LuAlignCenter,
  checkbox: LuCheck,
  'checkbox-card': LuSquareCheck,
  'close-button': LuX,
  code: LuCode,
  collapsible: LuChevronsUpDown,
  'color-swatch': LuPalette,
  container: LuContainer,
  'context-menu': LuEllipsis,
  counter: LuTimer,
  description: LuPilcrow,
  dialog: LuPanelTop,
  display: LuCaseSensitive,
  'design-grid': LuGrid3X3,
  drawer: LuPanelLeft,
  'dropdown-menu': LuChevronDown,
  'empty-state': LuInbox,
  field: LuNotebookText,
  flex: LuRows3,
  float: LuMove,
  grid: LuLayoutGrid,
  group: LuGroup,
  headline: LuCaseSensitive,
  highlight: LuHighlighter,
  'hover-card': LuPanelTopOpen,
  hstack: LuGalleryHorizontal,
  icon: LuAperture,
  'icon-box': LuPackage,
  'icon-button': LuSquareMousePointer,
  image: LuImage,
  input: LuType,
  'input-group': LuLibrary,
  'in-view': LuRoute,
  kbd: LuKeyboard,
  lead: LuCaseSensitive,
  link: LuLink,
  list: LuList,
  loader: LuLoader,
  logo: LuBadge,
  mark: LuPenLine,
  marquee: LuMoveHorizontal,
  menubar: LuRows3,
  'native-select': LuListChecks,
  'nav-button': LuNavigation,
  'nav-link': LuExternalLink,
  'navigation-menu': LuPanelsTopLeft,
  overlay: LuLayers,
  password: LuLock,
  'pin-input': LuHash,
  popover: LuPanelTopOpen,
  progress: LuChartNoAxesColumn,
  'progress-circle': LuCircleDashed,
  radio: LuCircle,
  'radio-card': LuCircleCheck,
  'scroll-area': LuScrollText,
  section: LuSection,
  select: LuChevronsUpDown,
  separator: LuSeparatorHorizontal,
  skeleton: LuLayoutTemplate,
  slider: LuSlidersHorizontal,
  stack: LuRows2,
  status: LuActivity,
  switch: LuToggleLeft,
  table: LuTable,
  tabs: LuKanban,
  text: LuLetterText,
  'text-slide': LuEqual,
  textarea: LuFileText,
  title: LuCaseSensitive,
  toast: LuBell,
  toggle: LuPower,
  'toggle-group': LuCombine,
  tooltip: LuInfo,
  triangle: LuTriangle,
  vstack: LuGalleryVertical,
} as const;
