name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Qwen2.5 Coder 7B Instruct
    provider: openai
    model: qwen2.5-coder-7b-instruct
    apiBase: http://127.0.0.1:1234/v1
    apiKey: ollama
    roles:
      - chat
      - edit
      - apply
      - autocomplete
  - name: Qwen2.5 Coder 1.5B Instruct
    provider: openai
    model: qwen2.5-coder-1.5b-instruct
    apiBase: http://127.0.0.1:1234/v1
    apiKey: ollama
    roles:
      - autocomplete
  - name: Autodetect
    provider: lmstudio
    model: AUTODETECT
    apiBase: http://localhost:1234/v1/
  - name: Qwen 2.5 Coder 7b
    provider: lmstudio
    model: qwen-coder2.5-7b
    apiBase: http://localhost:1234/v1/
