import {
  MenubarArrow,
  MenubarCheckboxItem,
  MenubarCommand,
  MenubarContent,
  MenubarIndicator,
  MenubarItem,
  MenubarLabel,
  MenubarMenu,
  MenubarPortal,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarRoot,
  MenubarSection,
  MenubarSeparator,
  MenubarSub,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarTrigger,
} from './menubar';

export type {
  MenubarArrowProps,
  MenubarCheckboxItemProps,
  MenubarCommandProps,
  MenubarContentProps,
  MenubarIndicatorProps,
  MenubarItemProps,
  MenubarLabelProps,
  MenubarMenuProps,
  MenubarPortalProps,
  MenubarProps,
  MenubarRadioGroupProps,
  MenubarRadioItemProps,
  MenubarSectionProps,
  MenubarSeparatorProps,
  MenubarSubContentProps,
  MenubarSubProps,
  MenubarSubTriggerProps,
  MenubarTriggerProps,
} from './menubar.types';

export const Menubar = Object.assign(MenubarRoot, {
  Arrow: MenubarArrow,
  CheckboxItem: MenubarCheckboxItem,
  Command: MenubarCommand,
  Content: MenubarContent,
  Item: MenubarItem,
  Indicator: MenubarIndicator,
  Label: MenubarLabel,
  Menu: MenubarMenu,
  Portal: MenubarPortal,
  RadioGroup: MenubarRadioGroup,
  RadioItem: MenubarRadioItem,
  Section: MenubarSection,
  Separator: MenubarSeparator,
  Sub: MenubarSub,
  SubContent: MenubarSubContent,
  SubTrigger: MenubarSubTrigger,
  Trigger: MenubarTrigger,
});
