import {
  ContextMenuCheckboxItem,
  ContextMenuCommand,
  ContextMenuContent,
  ContextMenuIndicator,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuPortal,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuRoot,
  ContextMenuSection,
  ContextMenuSeparator,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuTrigger,
} from './context-menu';

export type {
  ContextMenuCheckboxItemProps,
  ContextMenuCommandProps,
  ContextMenuContentProps,
  ContextMenuIndicatorProps,
  ContextMenuItemProps,
  ContextMenuLabelProps,
  ContextMenuPortalProps,
  ContextMenuProps,
  ContextMenuRadioGroupProps,
  ContextMenuRadioItemProps,
  ContextMenuSectionProps,
  ContextMenuSeparatorProps,
  ContextMenuSubContentProps,
  ContextMenuSubProps,
  ContextMenuSubTriggerProps,
  ContextMenuTriggerProps,
} from './context-menu.types';

export const ContextMenu = Object.assign(ContextMenuRoot, {
  CheckboxItem: ContextMenuCheckboxItem,
  Command: ContextMenuCommand,
  Content: ContextMenuContent,
  Item: ContextMenuItem,
  Indicator: ContextMenuIndicator,
  Label: ContextMenuLabel,
  Portal: ContextMenuPortal,
  RadioGroup: ContextMenuRadioGroup,
  RadioItem: ContextMenuRadioItem,
  Section: ContextMenuSection,
  Separator: ContextMenuSeparator,
  Sub: ContextMenuSub,
  SubContent: ContextMenuSubContent,
  SubTrigger: ContextMenuSubTrigger,
  Trigger: ContextMenuTrigger,
});
